### PR TITLE
Update data hourly using GitHub actions

### PR DESCRIPTION
**Pull request by foolip**

### CODE REVIEW

**Comment by foolip** [comment]
This probably doesn't work, but it's probably 80% there, just need to enable GitHub Actions to iterate on it until it works.

**Comment by foolip** [comment]
https://github.com/foolip/bikeshed-data/runs/206722597 ran this setup successfully, pushing https://github.com/foolip/bikeshed-data/commit/8b2173e4eafd224bdb512cfd625e28e2bf201958.

**Comment by tabatkins** [comment]
Cool, I'm just waiting for my beta invitation to come thru.

**Comment by foolip** [comment]
Great, as we found in https://github.com/plinss/widlparser/pull/48 it's not an instant process, but hopefully not long.

**Comment by tabatkins** [comment]
It looks like I'm in the beta now, so merging, and we'll see what happens.

**Comment by foolip** [comment]
Sweet, it has been working! https://github.com/tabatkins/bikeshed-data/commits/master

**Pull request merged**
